#!/usr/bin/env node
/**
 * scripts/coverage-report.js — field-coverage report generator (CI idea #2).
 *
 * Computes how completely each optional-but-important field is populated across
 * the dataset and writes `COVERAGE.md` (a table with progress bars). This
 * replaces the previously-manual coverage tallies posted to the data-lane
 * issues (#123/#161/#162/#177/#178/#179 …).
 *
 * The `build` workflow regenerates and commits this on every push to `main`, so
 * COVERAGE.md always reflects the live dataset. Run locally with:
 *   node scripts/coverage-report.js
 *
 * Pass a timestamp via COVERAGE_DATE=YYYY-MM-DD to make output deterministic
 * (CI passes the commit date); otherwise it is omitted.
 *
 * See docs/ci.md for the full CI overview.
 */
"use strict";
const fs = require("fs");
const path = require("path");

// Load the generated aggregate if present (fast), else read the source files.
let cameras;
const agg = path.join("data", "cameras.json");
if (fs.existsSync(agg)) {
  const parsed = JSON.parse(fs.readFileSync(agg, "utf8"));
  cameras = Array.isArray(parsed) ? parsed : parsed.cameras;
} else {
  cameras = [];
  for (const brand of fs.readdirSync("cameras")) {
    const dir = path.join("cameras", brand);
    if (!fs.statSync(dir).isDirectory()) continue;
    for (const f of fs.readdirSync(dir).filter((x) => x.endsWith(".json"))) {
      cameras.push(JSON.parse(fs.readFileSync(path.join(dir, f), "utf8")));
    }
  }
}

const T = cameras.length;

// Each lane: label, emoji, related issue, and a predicate for "populated".
const LANES = [
  ["Field of view", "📡", "#179", (c) => !!c.field_of_view_deg],
  ["Environment (in/outdoor)", "🌍", "#123", (c) => c.environment && c.environment.length > 0],
  ["Video streams", "🎞️", "#177", (c) => c.video && c.video.streams && c.video.streams.length > 0],
  ["Dimensions", "📐", "#178", (c) => !!c.dimensions_mm],
  ["Weight", "⚖️", "#178", (c) => c.weight_g != null],
  ["Markets", "🗺️", "#166", (c) => c.markets && c.markets.length > 0],
  ["Sensor", "🔬", "—", (c) => !!c.sensor],
  ["Lens", "🔎", "—", (c) => !!c.lens],
  ["Min-lux (color)", "🌙", "#161", (c) => c.night_vision && c.night_vision.min_lux_color != null],
  ["IK / impact rating", "🛡️", "#162", (c) => !!c.ik_rating],
  ["IP rating", "💧", "—", (c) => !!c.ip_rating],
  ["Frigate config", "🔧", "#170", (c) => c.configs && c.configs.frigate],
  ["Release year", "📅", "#166", (c) => c.release_year != null],
];

const bar = (pct) => {
  const filled = Math.round(pct / 10);
  return "`" + "█".repeat(filled) + "░".repeat(10 - filled) + "`";
};

const rows = LANES.map(([label, emoji, issue, pred]) => {
  const n = cameras.filter(pred).length;
  const pct = T ? Math.round((n / T) * 100) : 0;
  return { label, emoji, issue, n, pct };
}).sort((a, b) => b.pct - a.pct);

const brandCount = new Set(cameras.map((c) => c.brand)).size;
const date = process.env.COVERAGE_DATE && /^\d{4}-\d{2}-\d{2}$/.test(process.env.COVERAGE_DATE)
  ? process.env.COVERAGE_DATE
  : null;

let md = `# 📊 Field coverage\n\n`;
md += `> Auto-generated by \`scripts/coverage-report.js\` (do not edit by hand).`;
md += date ? ` Last updated: ${date}.\n\n` : `\n\n`;
md += `**${T.toLocaleString("en-US")} cameras** across **${brandCount} brands**.\n\n`;
md += `| Field | Coverage | Filled | Lane |\n`;
md += `|---|---|---:|:---:|\n`;
for (const r of rows) {
  const issueLink = r.issue.startsWith("#")
    ? `[${r.issue}](https://github.com/ch-bas/cctv-camera-database/issues/${r.issue.slice(1)})`
    : "";
  md += `| ${r.emoji} ${r.label} | ${bar(r.pct)} ${r.pct}% | ${r.n.toLocaleString("en-US")} | ${issueLink} |\n`;
}
md += `\nHelp raise a lane — see [open data-collection issues](https://github.com/ch-bas/cctv-camera-database/issues) (index: #163).\n`;

fs.writeFileSync("COVERAGE.md", md);
console.log(`Wrote COVERAGE.md — ${T} cameras, ${rows.length} lanes.`);
for (const r of rows) console.log(`  ${r.emoji} ${r.label.padEnd(26)} ${String(r.pct).padStart(3)}%  (${r.n})`);
